services:
  mediagui:
    container_name: mediagui
    image: ghcr.io/jbrodriguez/mediagui
    environment:
      - TZ=America/Panama
    volumes:
      - ${HOME}/.local/share/mediagui:/data
    ports:
      - "7623:7623"

