// Code generated by protoc-gen-go.
// source: agent.proto
// DO NOT EDIT!

/*
Package agent is a generated protocol buffer package.

It is generated from these files:
	agent.proto

It has these top-level messages:
	ScanReq
	ScanRsp
	ExistsReq
	ExistsRsp
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ScanReq struct {
	Folders []string `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
	Mask    string   `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *ScanReq) Reset()         { *m = ScanReq{} }
func (m *ScanReq) String() string { return proto.CompactTextString(m) }
func (*ScanReq) ProtoMessage()    {}

type ScanRsp struct {
	Filenames []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
}

func (m *ScanRsp) Reset()         { *m = ScanRsp{} }
func (m *ScanRsp) String() string { return proto.CompactTextString(m) }
func (*ScanRsp) ProtoMessage()    {}

type ExistsReq struct {
	Location string `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *ExistsReq) Reset()         { *m = ExistsReq{} }
func (m *ExistsReq) String() string { return proto.CompactTextString(m) }
func (*ExistsReq) ProtoMessage()    {}

type ExistsRsp struct {
	Exists bool `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
}

func (m *ExistsRsp) Reset()         { *m = ExistsRsp{} }
func (m *ExistsRsp) String() string { return proto.CompactTextString(m) }
func (*ExistsRsp) ProtoMessage()    {}
