// Code generated by protoc-gen-go.
// source: agent.proto
// DO NOT EDIT!

/*
Package agent is a generated protocol buffer package.

It is generated from these files:
	agent.proto

It has these top-level messages:
	ScanReq
	ScanRsp
	Item
	ExistsReq
	ExistsRsp
*/
package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScanReq struct {
	Folders []string `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
	Mask    string   `protobuf:"bytes,2,opt,name=mask" json:"mask,omitempty"`
}

func (m *ScanReq) Reset()                    { *m = ScanReq{} }
func (m *ScanReq) String() string            { return proto.CompactTextString(m) }
func (*ScanReq) ProtoMessage()               {}
func (*ScanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ScanRsp struct {
	Filenames []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
}

func (m *ScanRsp) Reset()                    { *m = ScanRsp{} }
func (m *ScanRsp) String() string            { return proto.CompactTextString(m) }
func (*ScanRsp) ProtoMessage()               {}
func (*ScanRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Item struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ExistsReq struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ExistsReq) Reset()                    { *m = ExistsReq{} }
func (m *ExistsReq) String() string            { return proto.CompactTextString(m) }
func (*ExistsReq) ProtoMessage()               {}
func (*ExistsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExistsReq) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ExistsRsp struct {
	Items []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ExistsRsp) Reset()                    { *m = ExistsRsp{} }
func (m *ExistsRsp) String() string            { return proto.CompactTextString(m) }
func (*ExistsRsp) ProtoMessage()               {}
func (*ExistsRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExistsRsp) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanReq)(nil), "ScanReq")
	proto.RegisterType((*ScanRsp)(nil), "ScanRsp")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*ExistsReq)(nil), "ExistsReq")
	proto.RegisterType((*ExistsRsp)(nil), "ExistsRsp")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3b, 0x4e, 0xc6, 0x30,
	0x10, 0x84, 0xe5, 0xfc, 0x09, 0xc1, 0x1b, 0x89, 0xc2, 0xa2, 0xb0, 0x80, 0x22, 0x72, 0x83, 0xab,
	0x14, 0x50, 0x70, 0x02, 0x24, 0x68, 0xcd, 0x09, 0x4c, 0xb2, 0x41, 0x16, 0x7e, 0x84, 0x78, 0x0b,
	0x8e, 0x8f, 0xf2, 0x02, 0xaa, 0xbf, 0xf3, 0x37, 0x9e, 0xd9, 0x59, 0x2d, 0x34, 0xf6, 0x03, 0x23,
	0x75, 0xd3, 0x9c, 0x28, 0xa9, 0x27, 0xa8, 0xdf, 0x7a, 0x1b, 0x0d, 0x7e, 0x09, 0x09, 0xf5, 0x98,
	0xfc, 0x80, 0x73, 0x96, 0xac, 0x3d, 0x69, 0x6e, 0x0e, 0x14, 0x02, 0xca, 0x60, 0xf3, 0xa7, 0x2c,
	0x5a, 0xa6, 0xb9, 0x59, 0xdf, 0xea, 0x7e, 0x0f, 0xe6, 0x49, 0xdc, 0x01, 0x1f, 0x9d, 0xc7, 0x68,
	0x03, 0x1e, 0xd1, 0x3f, 0x41, 0xbd, 0x40, 0xf9, 0x4a, 0x18, 0xc4, 0x15, 0x14, 0x6e, 0x90, 0xac,
	0x65, 0xba, 0x34, 0x85, 0x1b, 0xc4, 0x0d, 0x5c, 0xfa, 0xd4, 0x5b, 0x72, 0x29, 0xee, 0x83, 0x7f,
	0x59, 0x5c, 0x43, 0x45, 0x8e, 0x3c, 0xca, 0xd3, 0xfa, 0xb1, 0x81, 0xd2, 0xc0, 0x9f, 0xbf, 0x5d,
	0xa6, 0xbc, 0x6c, 0x7b, 0x0b, 0x95, 0x23, 0x0c, 0x5b, 0x61, 0xf3, 0x50, 0x75, 0x4b, 0x89, 0xd9,
	0xb4, 0x7f, 0xce, 0x3c, 0x9d, 0x75, 0xbe, 0x5f, 0xac, 0x67, 0x78, 0xfc, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xf0, 0x95, 0x4c, 0x15, 0x01, 0x00, 0x00,
}
