// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: mediaagent/agent.proto

package mediaagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Folders []string `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	Mask    string   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *ScanReq) Reset() {
	*x = ScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaagent_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanReq) ProtoMessage() {}

func (x *ScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_mediaagent_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanReq.ProtoReflect.Descriptor instead.
func (*ScanReq) Descriptor() ([]byte, []int) {
	return file_mediaagent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ScanReq) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *ScanReq) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type ScanRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filenames []string `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
}

func (x *ScanRsp) Reset() {
	*x = ScanRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaagent_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRsp) ProtoMessage() {}

func (x *ScanRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mediaagent_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRsp.ProtoReflect.Descriptor instead.
func (*ScanRsp) Descriptor() ([]byte, []int) {
	return file_mediaagent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ScanRsp) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaagent_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_mediaagent_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_mediaagent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ExistsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ExistsReq) Reset() {
	*x = ExistsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaagent_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsReq) ProtoMessage() {}

func (x *ExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_mediaagent_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsReq.ProtoReflect.Descriptor instead.
func (*ExistsReq) Descriptor() ([]byte, []int) {
	return file_mediaagent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ExistsReq) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ExistsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ExistsRsp) Reset() {
	*x = ExistsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaagent_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRsp) ProtoMessage() {}

func (x *ExistsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mediaagent_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRsp.ProtoReflect.Descriptor instead.
func (*ExistsRsp) Descriptor() ([]byte, []int) {
	return file_mediaagent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ExistsRsp) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_mediaagent_agent_proto protoreflect.FileDescriptor

var file_mediaagent_agent_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x27, 0x0a,
	0x07, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x33, 0x0a, 0x09, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x33, 0x0a, 0x09, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x7a, 0x0a, 0x0a, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e,
	0x12, 0x13, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x67,
	0x75, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mediaagent_agent_proto_rawDescOnce sync.Once
	file_mediaagent_agent_proto_rawDescData = file_mediaagent_agent_proto_rawDesc
)

func file_mediaagent_agent_proto_rawDescGZIP() []byte {
	file_mediaagent_agent_proto_rawDescOnce.Do(func() {
		file_mediaagent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_mediaagent_agent_proto_rawDescData)
	})
	return file_mediaagent_agent_proto_rawDescData
}

var file_mediaagent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mediaagent_agent_proto_goTypes = []interface{}{
	(*ScanReq)(nil),   // 0: mediaagent.ScanReq
	(*ScanRsp)(nil),   // 1: mediaagent.ScanRsp
	(*Item)(nil),      // 2: mediaagent.Item
	(*ExistsReq)(nil), // 3: mediaagent.ExistsReq
	(*ExistsRsp)(nil), // 4: mediaagent.ExistsRsp
}
var file_mediaagent_agent_proto_depIdxs = []int32{
	2, // 0: mediaagent.ExistsReq.items:type_name -> mediaagent.Item
	2, // 1: mediaagent.ExistsRsp.items:type_name -> mediaagent.Item
	0, // 2: mediaagent.MediaAgent.Scan:input_type -> mediaagent.ScanReq
	3, // 3: mediaagent.MediaAgent.Exists:input_type -> mediaagent.ExistsReq
	1, // 4: mediaagent.MediaAgent.Scan:output_type -> mediaagent.ScanRsp
	4, // 5: mediaagent.MediaAgent.Exists:output_type -> mediaagent.ExistsRsp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mediaagent_agent_proto_init() }
func file_mediaagent_agent_proto_init() {
	if File_mediaagent_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mediaagent_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaagent_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaagent_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaagent_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaagent_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mediaagent_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaagent_agent_proto_goTypes,
		DependencyIndexes: file_mediaagent_agent_proto_depIdxs,
		MessageInfos:      file_mediaagent_agent_proto_msgTypes,
	}.Build()
	File_mediaagent_agent_proto = out.File
	file_mediaagent_agent_proto_rawDesc = nil
	file_mediaagent_agent_proto_goTypes = nil
	file_mediaagent_agent_proto_depIdxs = nil
}
