// Code generated by protoc-gen-go.
// source: scan.proto
// DO NOT EDIT!

/*
Package scan is a generated protocol buffer package.

It is generated from these files:
	scan.proto

It has these top-level messages:
	Request
	Response
*/
package scan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	Folders []string `protobuf:"bytes,1,rep,name=folders" json:"folders,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Filenames []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
