#!/usr/bin/env bash

APPPATH="${HOME}/.mediagui"
BINPATH="${HOME}/bin"

# Use -gt 1 to consume two arguments per pass in the loop (e.g. each
# argument has a corresponding value to go with it).
# Use -gt 0 to consume one or more arguments per pass in the loop (e.g.
# some arguments don't have a corresponding value to go with it such
# as in the --default example).
# note: if this is set to -gt 0 the /etc/hosts part is not recognized ( may be a bug )
while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -a|--apppath)
    APPPATH="$2"
    shift # past argument
    ;;
    -b|--binpath)
    BINPATH="$2"
    shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

BACKUP=`date +"%Y%m%d"`

echo "APPPATH = ${APPPATH}"
echo "BINPATH = ${BINPATH}"
echo "BACKUP = ${BACKUP}"

# Don't backup img folder. It's too big
mv ${APPPATH}/web/img ${APPPATH}/

# Backup current code
mkdir -p ${APPPATH}/bck/${BACKUP}
mv ${APPPATH}/web/* ${APPPATH}/bck/${BACKUP}
mv ${BINPATH}/mediagui ${APPPATH}/bck/${BACKUP}

# Copy client code
cp -R ./client/* ${APPPATH}/web/

# Move back img folder
mv ${APPPATH}/img ${APPPATH}/web

# Copy binary to binary folder
cp ./server/mediagui ${BINPATH}

# Copy agent
scp ./agent/agent root@wopr:/boot
scp ./agent/agent root@hal:/boot