export const FETCH_CONFIG = 'FETCH_CONFIG';
export const FETCH_COVER = 'FETCH_COVER';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
